# Generated by Django 5.1.2 on 2024-11-11 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0002_sliderimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4)),
                ('quantity', models.CharField(max_length=2)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=70)),
                ('price', models.ForeignKey(db_column='price', on_delete=django.db.models.deletion.CASCADE, to='bloodapp.bloodsell')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
