# Generated by Django 5.1.2 on 2024-11-14 13:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0003_confirmorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Confirmorder',
            new_name='Confirmbuydetails',
        ),
    ]
