# Generated by Django 5.1.2 on 2024-11-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0004_rename_confirmorder_confirmbuydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmbuydetails',
            name='total_price',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]
