# Generated by Django 5.1.2 on 2024-11-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0005_confirmbuydetails_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmbuydetails',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
